### PR TITLE
Re-enable functional tests

### PR DESCRIPTION
**Pull request by shartte**

### CODE REVIEW

**Comment by marchermans** [comment]
That is actually on my plan, but I wanted to rewrite them to the new scheme in training wheels. 
There is now a builder based approach to this, which should allow making these tests a lot easier.

Do you just want to focus on enabling them, or do you want to also work on porting them to that scheme?

**Comment by shartte** [comment]
Oh no trouble, I can port to that new scheme, I just wasn't sure if it was the future or not, heh

**Comment by marchermans** [comment]
> Oh no trouble, I can port to that new scheme, I just wasn't sure if it was the future or not, heh

They sure as hell are. Hey support more scenarios and have a much simpler handling.

**Comment by marchermans** [comment]
This has been implemented.

**Pull request closed without merging**
