### PR TITLE
Fix string delimiters for Gradle dependencies in README.md

### PR DESCRIPTION
**Pull request by qtdyn**
:)

### CODE REVIEW

**Comment by Technici4n** [comment]
The `"` is required for string interpolation, so no.

**Comment by dynpatch** [comment]
So it can be changed to both double-quotes then?

**Comment by Technici4n** [comment]
Ahhh yes that is fine

**Comment by dynpatch** [comment]
Sorry I wasn't thinking of interpolation when changing this :sweat:

**Comment by Technici4n** [comment]
Apparently Orion already fixed this?

**Comment by dynpatch** [comment]
Yup, case closed

**Pull request closed without merging**
